Fix test failures in auth-backends on latest version of pyjwt
edx/auth-backends pull request #93
Opened 2021-01-23 09:31 UTC by awais786

https://openedx.atlassian.net/browse/BOM-2194

Fix test failures in auth-backends on latest version of pyjwt

2021-01-23 18:38 UTC, mzulqarnain1 approved these changes

2021-01-25 09:28 UTC, mzulqarnain1 requested changes
Bump version for the PyPI release, please.

2021-01-26 07:49 UTC, mraarif approved these changes

2021-01-26 07:51 UTC, mzulqarnain1 approved these changes

2021-01-26 07:55 UTC, merged